### ISSUE TITLE
Sub-workflow for gene annotation

### ISSUE THREAD

**Issue by anwarMZ** [cidgoh/nf-seqqc#32]
### Description of feature

Create a sub-workflow of gene annotation using the following modules from nf-core

- [x] [Bakta](https://github.com/nf-core/modules/tree/master/modules/nf-core/bakta)
- [x] [Prokka](https://github.com/nf-core/modules/tree/master/modules/nf-core/prokka)

**Comment by jimmyliu1326** [comment]
Completed by #44
