### ISSUE TITLE
Create a nextflow module for eggnog-mapper2

### ISSUE THREAD

**Issue by jimmyliu1326** [cidgoh/nf-seqqc#37]
### Description of feature

eggnog-mapper2 is not available through nf-core. Write a nf-core standard [eggnog-mapper2](https://github.com/eggnogdb/eggnog-mapper) module

- [ ] include a Singularity/docker container
- [ ] include a bioconda container

**Comment by anwarMZ** [comment]
@jimmyliu1326 we can skip making this - There is eggnog-mapper module in nf-core ready to be merged soon https://github.com/nf-core/modules/commit/18cd2206622dc606bbceea533c7823feb2a251db
