### ISSUE TITLE
Sub-workflow for pangenome analysis

### ISSUE THREAD

**Issue by anwarMZ** [cidgoh/nf-seqqc#38]
### Description of feature

Create sub-workflow for pangenome analysis using the following nf-core modules

- [x] [roary](https://github.com/nf-core/modules/tree/1e729660254e84bf0b6451a94b3ca511b6a3d1e4/modules/nf-core/roary)
- [x] [pirate](https://github.com/nf-core/modules/tree/1e729660254e84bf0b6451a94b3ca511b6a3d1e4/modules/nf-core/pirate)
- [x] [panaroo](https://github.com/nf-core/modules/tree/1e729660254e84bf0b6451a94b3ca511b6a3d1e4/modules/nf-core/panaroo)

The following modules require writing nextflow modules before integration

- [x] [peppan ](https://github.com/zheminzhou/PEPPAN)

**Comment by anwarMZ** [comment]
#40 is required for closing this issue

**Comment by jonathho** [comment]
Manually added in module for PEPPAN from #40 to make merging easier

**Comment by jimmyliu1326** [comment]
Completed by #55
