### ISSUE TITLE
Create a nextflow module for PEPPAN

### ISSUE THREAD

**Issue by anwarMZ** [cidgoh/nf-seqqc#40]
### Description of feature

PEPPAN is not available through nf-core. Write a nf-core standard [PEPPAN](https://github.com/zheminzhou/PEPPAN) module

- [x]  include a Singularity/docker container
- [ ]  include a bioconda container

**Comment by azmigueldario** [comment]
Could not make the conda environment work, finished module

**Comment by jimmyliu1326** [comment]
Completed by #38
